--○ 10일차
-- 1번
SELECT MGR, EMPNO, ENAME, SYS_CONNECT_BY_PATH(ENAME, ' > ') RELATION
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR;

-- 2번
SELECT MGR, EMPNO, ENAME, SYS_CONNECT_BY_PATH(ENAME, ' > ') RELATION
FROM EMP
START WITH MGR=(SELECT EMPNO FROM EMP WHERE ENAME='JONES')
CONNECT BY PRIOR EMPNO = MGR;

-- 3번
SELECT MGR, EMPNO, ENAME, SYS_CONNECT_BY_PATH(ENAME, ' > ') RELATION
FROM EMP
START WITH EMPNO = (SELECT MGR FROM EMP WHERE ENAME='ALLEN')
CONNECT BY PRIOR MGR = EMPNO;

-- 4번
SELECT LEVEL AS DEPTH, MGR, EMPNO, ENAME, SYS_CONNECT_BY_PATH(ENAME, ' > ') RELATION
FROM EMP
START WITH EMPNO = 7698 OR EMPNO = 7782
CONNECT BY PRIOR EMPNO = MGR;

-- 5번
SELECT LEVEL AS DEPTH, MGR, EMPNO, ENAME, SYS_CONNECT_BY_PATH(ENAME, ' > ') RELATION
FROM EMP
WHERE CONNECT_BY_ISLEAF = 1
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR