--○ 11일차
-- 1번
SELECT JOB, SUM(SAL) "급여합계"
FROM EMP
WHERE JOB != 'SALESMAN'
GROUP BY JOB
HAVING SUM(SAL) > 5000;

-- 2번
SELECT D.DNAME, COUNT(E.EMPNO) "사원수", SUM(E.SAL) "SUM(SAL)"
FROM EMP E JOIN DEPT D ON E.DEPTNO=D.DEPTNO
GROUP BY D.DNAME
HAVING COUNT(E.EMPNO) >= 3

-- 3번
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB
HAVING MIN(SAL) > 1000;
