--○ 11일차
-- 1번
SELECT JOB, SUM(SAL) "급여합계"
FROM EMP
WHERE JOB != 'SALESMAN'
GROUP BY JOB
HAVING SUM(SAL) > 5000;

-- 2번
SELECT DNAME, COUNT(*) "사원수", SUM(SAL)
FROM
(
    SELECT D.DNAME, E.EMPNO, E.SAL
    FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
)
GROUP BY DNAME
HAVING COUNT(*) >= 3;

-- 3번
SELECT JOB, SUM(SAL)
FROM EMP
GROUP BY JOB
HAVING MIN(SAL) > 1000;
