-- ○12일차
-- 1번
SELECT E.EMPNO, E.ENAME, D.DNAME, D.LOC
FROM EMP E LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO
WHERE NOT EXISTS (SELECT 1
                  FROM DUAL 
                  WHERE D.LOC IN ( 'BOSTON', 'CHICAGO'));

-- 2번
SELECT LEVEL AS DEPTH, CONNECT_BY_ROOT EMPNO AS ROOT, MGR, EMPNO, ENAME, SYS_CONNECT_BY_PATH(ENAME, ' > ') RELATATION
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR;

-- 3번
CREATE INDEX EMP_IDX01 ON EMP(EMPNO DESC);

SELECT /*+ INDEX(E EMP_IDX01) */ E.*
FROM EMP E;