-- ○12일차
-- 1번
SELECT *
FROM
(
SELECT E.EMPNO, E.ENAME, D.DNAME, D.LOC
FROM EMP E LEFT JOIN DEPT D ON E.DEPTNO = D.DEPTNO
) T1
WHERE NOT EXISTS (SELECT LOC
                  FROM DEPT 
                  WHERE T1.LOC IN ( 'BOSTON', 'CHICAGO'));

-- 2번
SELECT LEVEL AS DEPTH, CONNECT_BY_ROOT EMPNO AS ROOT, MGR, EMPNO, ENAME, SYS_CONNECT_BY_PATH(ENAME, ' > ') RELATATION
FROM EMP
START WITH MGR IS NULL
CONNECT BY PRIOR EMPNO = MGR;

-- 3번
CREATE INDEX EMP_IDX01 ON EMP(EMPNO DESC);
DROP INDEX EMP_IDX01;

CREATE INDEX EMP_IDX02 ON EMP(ENAME DESC);
DROP INDEX EMP_IDX02;

SELECT TABLE_NAME, INDEX_NAME, COLUMN_POSITION, COLUMN_NAME
FROM USER_IND_COLUMNS
WHERE TABLE_NAME = 'EMP'

EXPLAIN PLAN FOR
SELECT /*+ INDEX(E EMP_IDX01) */ E.*
FROM EMP E;

SELECT *
FROM TABLE(DBMS_XPLAN.DISPLAY);

SELECT NAME, VALUE, ISDEFAULT, ISMODIFIED, DESCRIPTION
FROM V$PARAMETER
WHERE NAME LIKE '%optimizer_mode%';