--○ 9일차 
-- 1번
SELECT DEPTNO
     , JOB
     , SUM(SAL) SUM_SAL
FROM EMP
WHERE DEPTNO IS NOT NULL
GROUP BY ROLLUP(DEPTNO, JOB)
ORDER BY DEPTNO;

-- 2번
SELECT DEPTNO
     , JOB
     , SUM(SAL) SUM_SAL
FROM EMP
WHERE DEPTNO IS NOT NULL
GROUP BY CUBE(DEPTNO, JOB);

-- 3번
SELECT NVL(D.DNAME, '합계') AS DNAME
     , CASE GROUPING_ID(D.DNAME, E.JOB) WHEN 1 THEN '소계'
                                        WHEN 0 THEN E.JOB
                                        ELSE ' ' END JOB
     , SUM(E.SAL) SUM_SAL
FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
GROUP BY ROLLUP(D.DNAME, E.JOB)
ORDER BY GROUPING(D.DNAME), DNAME DESC, GROUPING(E.JOB)

-- 4번
SELECT CASE WHEN T.RANK = 1 THEN T.DNAME
            ELSE ' '
            END DNAME
     , T.JOB
     , T.SUM_SAL
FROM
(
    SELECT CASE WHEN GROUPING(D.DNAME) = 1 THEN '합계'
                ELSE D.DNAME
                END DNAME
         , CASE WHEN GROUPING_ID(D.DNAME, E.JOB) = 1 THEN '소계'
           WHEN GROUPING_ID(D.DNAME, E.JOB) = 0 THEN E.JOB
           ELSE ' '
           END JOB 
         , REGEXP_REPLACE(REVERSE(
             REGEXP_REPLACE(REVERSE(TO_CHAR(SUM(E.SAL))), '(\d{3})', '\1,'))
               , '^,', '') AS SUM_SAL 
         , RANK() OVER (PARTITION BY D.DNAME ORDER BY E.JOB) RANK
    FROM EMP E JOIN DEPT D ON E.DEPTNO = D.DEPTNO
    GROUP BY ROLLUP ( D.DNAME, E.JOB)
    ORDER BY GROUPING(D.DNAME), DNAME, GROUPING(E.JOB), JOB
) T;

-- 5번
SELECT CASE RANK WHEN 1 THEN DNAME
                 ELSE ' ' END DNAME
     , JOB, SUM_SAL
FROM
(
    SELECT NVL(T.DNAME,'합계') DNAME
         , CASE GROUPING_ID(T.DNAME, T.JOB) WHEN 0 THEN T.JOB
                                            WHEN 1 THEN '소계'
                                            ELSE ' ' END JOB
         , REGEXP_REPLACE(REVERSE(REGEXP_REPLACE(REVERSE(TO_CHAR(SUM(T.SAL))), '(\d{3})', '\1,')), '^,', '') AS SUM_SAL
         , RANK() OVER (PARTITION BY T.DNAME ORDER BY T.JOB) RANK
    FROM
    (
        SELECT D.DNAME, E.JOB, SUM(E.SAL) SAL
        FROM DEPT D JOIN EMP E ON D.DEPTNO = E.DEPTNO
        GROUP BY D.DNAME, E.JOB
    ) T
    WHERE T.SAL >= 1000
    GROUP BY ROLLUP(T.DNAME, T.JOB)
)